SECTION TEXT
meuCol:extern
INPUT OLD_DATA
LOAD OLD_DATA
PUBLIC MEUOVO
PUBLIC seguraPeao
l3: Extern
L1: DIV meucol
STORE  NEW_DATA
ljdai: extern
MULT meucol
STORE TMP_DATA
LOAD OLD_DATA
segurapeao: SUB TMP_DATA
STORE meucol
OUTPUT meuCol
COPY NEW_DATA,OLD_DATA
LOAD ljdai
meuovo:JMPP meucol
STOP
SECTION DATA
DOIS: CONST 2
OLD_DATA: SPACE
NEW_DATA: SPACE
TMP_DATA: SPACE
